---
- name: Configure Cisco Nexus Interfaces
  hosts: all
  gather_facts: no

  tasks:
    - name: Render interface configuration
      template:
        src: ../templates/interface_config.j2
        dest: ./tmp/interface_config_{{ inventory_hostname }}.cfg
      register: rendered

    - name: Push config to Nexus switch
      nxos_config:
        src: ../tmp/interface_config_{{ inventory_hostname }}.cfg
        save_when: modified
      when: rendered.changed