---
- name: "CONFIG DEVICE INTERFACES"
  hosts: leaf
  gather_facts: no

  tasks:
#==================================== SEND COMMAND CONFIG TASK =====================================
  # tasks send command to configure using "arista.eos.eos_config"

    - name: Send command to configure
      cisco.nxos.nxos_config:
        lines:
          - hardware access-list tcam region racl 512
          - hardware access-list tcam region arp-ether 256 double-wide


