---
# task/system_init.yml 
- name: "CONFIG BASIC SYSTEM "
  hosts: all
  gather_facts: no

  tasks:
#==================================== INIT SYSTEM TASK =====================================
  # tasks remove and configure for banner using "arista.eos.eos_banner"
 
    - name: Remove unneeded banners
      eos_banner:
        banner: "{{ item }}"
        state: absent
      loop:
      - motd

    - name: Update login banner
      eos_banner:
        banner: login
        text: |
           ********************************************************
           Grit:The power of passion and perseverance prohibited.
            _      ____  _       _____       _               ____  
           | |    |___ \| |     / ____|     | |        /\   |  _ \ 
           | |      __) | |    | (___ ______| |       /  \  | |_) |
           | |     |__ <| |     \___ \______| |      / /\ \ |  _ < 
           | |____ ___) | |____ ____) |     | |____ / ____ \| |_) |
           |______|____/|______|_____/      |______/_/    \_\____/ 
           
           *************** You are logged into {{ inventory_hostname }} *****************
        state: present

  # tasks configure name server and ntp

    - name: configure command list
      eos_config:
        lines:
          - ip name-server vrf mgmt {{name_servers}}
          - clock timezone {{timezone}}
          - no ip name-server vrf default 8.8.4.4
          - no ip name-server vrf default 8.8.4.4

    - name: configure DNS lookup sources with VRF support
      arista.eos.eos_system:
        lookup_source:
          - interface: Management1
            vrf: mgmt

    - name: configure name servers 
      arista.eos.eos_system:
        name_servers:
          - 8.8.8.8
          - 8.8.4.4
        state: absent

    - name: configure replace ntp-global
      arista.eos.eos_ntp_global:
        config:
          servers:
            - server: "{{ntp_servers.server1}}"
              vrf: "mgmt"
            - server: "{{ntp_servers.server2}}"
              vrf: "mgmt"		  
        state: replaced

  # tasks configure syslog server and logging

    - name: Configure syslog
      eos_logging:
        dest: host
        name: "{{ log_host }}"
        state: present
    
    - name: Set log source
      eos_config:
        lines:
          - logging source-interface {{mgmt_interface}}
    
    - name: Configure log buffer
      eos_logging:
        dest: buffered
        level: informational
        size: 5000
        state: present