---
- name: Configure Cisco Nexus Interfaces
  hosts: L1
  gather_facts: no
  # vars_files:
  #   - vars/interfaces.yml

  tasks:
    - name: Render interface configuration
      template:
        src: ../templates/interface_config.j2
        dest: /tmp/interface_config.cfg

    - name: Push config to Nexus switch
      nxos_config:
        src: /tmp/interface_config.cfg
        save_when: modified
