---
- name: Generate BGP configuration for all devices
  hosts: all
  gather_facts: false

  tasks:
    - name: Render BGP configuration
      template:
        src: ../templates/bgp_config.j2
        dest: ../tmp/bgp_config_{{ inventory_hostname }}.cfg
      delegate_to: localhost
