---
# task/system_init.yml 
- name: "CONFIG BASIC SYSTEM "
  hosts: L1
  gather_facts: no

  tasks:
#==================================== INIT SYSTEM TASK =====================================
  # config hostname and domain name

    - name: Configure hostname and domain name
      nxos_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ domain_name }}"

    - name: configure name servers with VRF support
      cisco.nxos.nxos_system:
        name_servers:
          - server: "{{ item }}"
            vrf: "{{ mgmt_vrf }}"
      loop: "{{ name_servers }}"
