---
- name: Configure Cisco Nexus OSPF
  hosts: all
  gather_facts: no
  # vars_files:
  #   - vars/interfaces.yml

  tasks:
    - name: Enable OSPF feature (required)
      cisco.nxos.nxos_feature:
        feature: ospf
        state: enabled

    - name: Delete all OSPF processes from the device
      cisco.nxos.nxos_ospfv2:
        state: deleted

    - name: Configure OSPF process
      cisco.nxos.nxos_ospfv2:
        config:
          processes:
            - process_id: "UNDERLAY_OSPF"
              router_id: "{{ RID }}"
              passive_interface: 
                default: true
              log_adjacency_changes:
                log: true                            
              areas:
                - area_id: "0.0.0.0"
                  authentication:
                    message_digest: true
        state: merged