---
- name: Save running config to starup config
  hosts: uat
  gather_facts: no
  become: no

  tasks:
  - name: SAVE CONFIG EOS
    eos_command:
      commands:
        - write memory
    when: ansible_network_os == 'arista.eos.eos'

  - name: SAVE CONFIG NXOS
    nxos_command:
      commands:
        - copy run start
    when: ansible_network_os == 'cisco.nxos.nxos'   