---
# leaf 2
RID: 2.2.2.2
Loopback0: 10.0.0.12
interfaces:
  - name: "1/1"    
    description: "SPINE-1"    
    ip: 10.1.2.2/30    
  - name: "1/2"    
    description: "SPINE-2"    
    ip: 10.2.2.2/30
vlans_local:
  - 10
  - 20
edge_interfaces:
  # 1/3:
  #   description: "Downlink to PC"
  #   port_type: "edge"
  #   mode: "access"
  #   access_vlan: 20
  #   spanning_tree: "edge"
  #   bpduguard: "enable"

  1/3:
    description: "ESXi Host"
    port_type: "edge"
    mode: "trunk"
    trunk_allowed: "10,20"
    # native_vlan: "20"
    spanning_tree: "trunk"
